name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Python
      uses: actions/setup-python@v4.0.0

        
    - name: Update paper list
      run: python main.py
